# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
# issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="hcutilsmod" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
# A display name for the mod
displayName="サバイバルで便利なMOD集" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/hcutilsmod" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png" #optional
# 素材提供
# https://icon-icons.com/ja/%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3/%E3%81%8A%E4%BA%92%E3%81%84%E3%81%AB%E5%B9%B4%E9%BD%A2%E3%81%AF%E5%90%8C%E5%B9%B4%E4%BB%A3%E3%81%A7-%E6%89%80%E5%B1%9E/94415
# https://hpgpixer.jp/
# A text field displayed in the mod UI
# credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="ハタボー" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
マイクラのサバイバルで便利なMODを作ります。
※当MODの使用は自己責任でお願いします。

#01 ブロックの方向を変える（シングルプレイのみ）
#02 座標だけ表示する
#03 インベントリを整理する（シングルプレイのみ）
#04 手持ちを使い切ったら自動で補充する（シングルプレイのみ）
#05 スポナーを見つける
#06 明るさマーカーを表示する（Ver.1.53～）
#07 スクリーンショットのツイート（Windows版のみ Ver.1.6～）

※当MODは「#07 スクリーンショットのツイート」でtwitter4jを
  利用しています。感謝！
  https://twitter4j.org/ja/
  暗号化を行うためあなたのユーザーディレクトリにファイルを作成します。
  ご了承ください。

--------
Ver.1.6
--------
2022/3/6
・「#07 スクリーンショットのツイート」を追加した。
--------
Ver.1.56
--------
2022/3/6
・forge-1.18.1-39.1.0-mdkに更新。正式リリース。
・チャットなどの文字入力でMODのキーが反応してしまっていたバグの修正
--------
Ver.1.55
--------
2022/1/24
・forge-1.18.1-39.0.59-mdkに更新
・牛から牛乳を汲み取ったらバケツが消えるバグの修正
--------
Ver.1.54
--------
2022/1/16
・設定の誤字などを修正。
・通じるかわからんが英語に対応してみた。※一部英訳できず。
--------
Ver.1.53
--------
2022/1/7
・forge-1.18.1-39.0.10-mdkに更新
・明るさマーカーを表示する機能の追加
（ブロックの変化による更新をちゃんと検知できてない）
--------
Ver.1.52
--------
2021/12/11
・forge-1.18-38.0.17-mdkに更新
・ブロックの方向を変えるデフォルトキーを[SHIFT+r]から[r]に変更した。
（OptiFineと一緒に導入するとなぜかSHIFTが無効化されてしまうので・・・）
--------
Ver.1.51
--------
2021/12/01
・forge-1.18-38.0.8-mdkに更新
・スタックできないアイテムの自動補充のバグを修正
--------
Ver.1.5
--------
2021/10/02
・インベントリのソートにカテゴリ順を追加
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.hcutilsmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[35,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.hcutilsmod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
